const SkillsData = {
  "Programming Languages & Development": [
    "Python",
    "Java",
    "SQL",
    "Flutter SDK",
    "C#",
    "Powershell (WPF)",
    "MATLAB",
    "Dart",
    "Unity 2D",
  ],
  "Data Science & Data Analytics": [
    "Neural Networks",
    "TensorFlow",
    "Tableau",
    "Keras",
    "Bayesian Optimization",
    "FastAPI",
    "Machine Learning Models",
  ],
  "Tools": [
    "BigQuery",
    "Git",
    "GitHub",
    "Jira",
    "Azure",
    "ElasticSearch",
    "Kibana",
    "GCP",
    "Firebase",
    "ANSYS",
    "Streamlit",
    "Bash",
  ],
  "Mechanical & Electrical": [
    "3D CAD (Fusion 360, Solidworks, Siemens NX)",
    "FEA Simulation",
    "Avionics",
    "Airworthiness Analysis",
    "GD&T",
    "CANBUS",
    "Eagle Schematics and Circuits",
    "Embedded Systems & IoT",
  ],
};

export default SkillsData;
